apiVersion: v1
kind: Service
metadata:
  name: jenk_slave_svc
  namespace: jenkins
spec:
  selector:
    app: jenkins-deploy
  type: ClusterIP 
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
