---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins_admin
rules:
  - apiGroups: ['']
    resources: ['*']
    verbs: ['*']
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins_admin
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins_admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins_admin
subjects:
  - kind: ServiceAccount
    name: jenkins_admin
    namespace: jenkins